#!/bin/sh
ROOT=$(readlink -f $(dirname $0)/..)

$ROOT/bin/piggly trace && \
  (ruby -I"$ROOT/lib" `find $ROOT/example/test/ -name '*_test.rb'` 2>trace.txt) && \
  $ROOT/bin/piggly report -f trace.txt

$ROOT/bin/piggly untrace
