#!/bin/sh
set -e
set -x

ROOT=$(dirname $0)/..
EXAMPLE="$ROOT/example"

"$ROOT/bin/piggly" trace \
  -d "$EXAMPLE/config/database.yml" \
  -o "$EXAMPLE/piggly/reports" \
  -c "$EXAMPLE/piggly/cache"

bundle exec rspec -I"$ROOT/lib" $(find "$EXAMPLE/spec/" -name '*_spec.rb') 2>"$EXAMPLE/trace.txt"

"$ROOT/bin/piggly" report \
  -o "$EXAMPLE/piggly/reports" \
  -c "$EXAMPLE/piggly/cache" \
  -f "$EXAMPLE/trace.txt"

"$ROOT/bin/piggly" untrace \
  -d "$EXAMPLE/config/database.yml" \
  -c "$EXAMPLE/piggly/cache"

echo "OK, view $EXAMPLE/piggly/reports/index.html"
